package com.linkpal.integrated.test;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * Description:
 *
 * @author lichao
 * @date 2019年12月19日 下午2:24:05
 *
 */
public class TestJsonObject {
	
	public static void main(String[] args) {
		JSONObject sendJsonObject = new JSONObject();
		
		JSONObject dataJsonObj = new JSONObject();
		
		JSONArray page1Array = new JSONArray();
		JSONObject page1JsonObj = new JSONObject();
		page1JsonObj.put("FBillNo", "CGZP000306");
		JSONObject itemClassObj= new JSONObject();
		itemClassObj.put("FNumber","008");
		itemClassObj.put("FName","");
		page1JsonObj.put("FItemClassID",itemClassObj);
		JSONObject supplyObj = new JSONObject();
		supplyObj.put("FNumber","02.05");
		supplyObj.put("FName","");
		page1JsonObj.put("FSupplyID", supplyObj);
		page1JsonObj.put("FDate", "2019-12-18");
		page1JsonObj.put("FFincDate", "2019-12-18");
		JSONObject exchangeRateTypeObj = new JSONObject();
		exchangeRateTypeObj.put("FNumber","01");
		exchangeRateTypeObj.put("FName","");
		page1JsonObj.put("FExchangeRateType", exchangeRateTypeObj);
		page1JsonObj.put("FClassTypeID", 1000004);
		JSONObject currencyObj = new JSONObject();
		currencyObj.put("FNumber","RMB");
		currencyObj.put("FName","");
		page1JsonObj.put("FCurrencyID", currencyObj);
		page1JsonObj.put("FExchangeRate", "1");
		page1JsonObj.put("FInterestRate", 0.0);
		JSONObject acttObj = new JSONObject();
		acttObj.put("FNumber","1122.01");
		acttObj.put("FName","");
		page1JsonObj.put("FAcctID", acttObj);
		page1JsonObj.put("FAdjustExchangeRate", 1.0);
		JSONObject poStyleObj = new JSONObject();
		poStyleObj.put("FNumber","");
		poStyleObj.put("FName","");
		page1JsonObj.put("FPOStyle", poStyleObj);
		page1JsonObj.put("FNote", "付某某供应商某产品费用款");
		page1JsonObj.put("FCompactNo", "");
		page1JsonObj.put("FTotalCostFor", 58.5);
		page1JsonObj.put("FTotalCost", 0);
		page1JsonObj.put("FSourceBillType", "");
		page1JsonObj.put("FSourceBillNo1", "");
		JSONObject deptObj = new JSONObject();
		deptObj.put("FNumber","01.02.058");
		deptObj.put("FName","");
		page1JsonObj.put("FDeptID", deptObj);
		JSONObject empObj = new JSONObject();
		empObj.put("FNumber","10112286");
		empObj.put("FName","");
		page1JsonObj.put("FEmpID", empObj);
		JSONObject billerObj = new JSONObject();
		billerObj.put("FNumber","郭林");
		billerObj.put("FName","");
		page1JsonObj.put("FBillerID", billerObj);
		JSONObject resourceObj = new JSONObject();
		resourceObj.put("FNumber","");
		resourceObj.put("FName","");
		page1JsonObj.put("FResourceID", resourceObj);
		page1JsonObj.put("FBillerName", "");
		JSONObject taskObj = new JSONObject();
		taskObj.put("FNumber","");
		taskObj.put("FName","");
		page1JsonObj.put("FTaskID", taskObj);
		JSONObject checkerObj = new JSONObject();
		checkerObj.put("FNumber","郭林");
		checkerObj.put("FName","");
		page1JsonObj.put("FCheckerID", checkerObj);
		page1JsonObj.put("FBudgetAmountFor", 0.0);
		page1JsonObj.put("FPosterID", 16401);
		JSONObject orderObj = new JSONObject();
		orderObj.put("FNumber","");
		orderObj.put("FName","");
		page1JsonObj.put("FOrderID", orderObj);
		page1JsonObj.put("FBank", "");
		page1JsonObj.put("FOrderAmountFor", 0);
		page1JsonObj.put("FAddress", "");
		page1JsonObj.put("FVchInterID", "");
		page1JsonObj.put("FTaxNum", "");
		page1JsonObj.put("FAccount", "");
		page1JsonObj.put("FTotalExpenseFor", 0);
		page1JsonObj.put("FTotalExpense", "");
		page1JsonObj.put("FBillStatus", "");
		page1JsonObj.put("FOffsetTaxFor", 0);
		page1JsonObj.put("FOffsetTax", "");
		page1JsonObj.put("FFreeItem3", "");
		page1JsonObj.put("FROB", "");
		page1JsonObj.put("FTranType", "");
		page1JsonObj.put("FFreeItem4", "");
		page1JsonObj.put("FVoucherInterID", "");
		page1JsonObj.put("FArApStatus", 7);
		page1JsonObj.put("FAdjustAmount", 0);
		page1JsonObj.put("FYear", 2019);
		page1JsonObj.put("FPeriod", 12);
		page1JsonObj.put("FPrintCount", 0);
		page1JsonObj.put("FSubSystemID", 1);
		page1JsonObj.put("FYearPeriod", "");
		JSONObject hookerObj = new JSONObject();
		hookerObj.put("FNumber","");
		hookerObj.put("FName","");
		page1JsonObj.put("FHookerID", hookerObj);
		page1JsonObj.put("FRegion", null);
		page1JsonObj.put("FTrade", null);
		page1JsonObj.put("FCheckAmountForBill", 102000);
		page1JsonObj.put("FCheckAmountBill", 102000);
		page1JsonObj.put("FRemainAmountForBill", "");
		page1JsonObj.put("FRemainAmountBill", 0);
		page1JsonObj.put("FCheckDate", "");
		page1JsonObj.put("FStatus", 0);
		page1JsonObj.put("FSysStatus", 2);
		page1JsonObj.put("FObtainRateWay", 0);
		page1JsonObj.put("FLockBill", "");
		JSONObject baseObj = new JSONObject();
		baseObj.put("FNumber","");
		baseObj.put("FName","");
		page1JsonObj.put("FBase", baseObj);
		page1JsonObj.put("FBaseProperty", "");
		page1JsonObj.put("FJSBillNo", "");
		JSONObject payConditionObj = new JSONObject();
		payConditionObj.put("FNumber","");
		payConditionObj.put("FName","");
		page1JsonObj.put("FPayCondition", payConditionObj);
		page1JsonObj.put("FJSDate", null);
		page1JsonObj.put("FBillDiscount", "");
		page1JsonObj.put("FBillDiscountRate", "");
		page1Array.add(page1JsonObj);
		
		JSONArray page2Array = new JSONArray();
		JSONObject page2JsonObj = new JSONObject();
		page2JsonObj.put("FEntryID2", 1);
		page2JsonObj.put("fdate_2", "2019-12-18");
		page2JsonObj.put("FAmountFor", "102000");
		page2JsonObj.put("FOrgID", 131);
		page2JsonObj.put("FAmount2", "");
		page2JsonObj.put("FRemainAmount", "");
		page2JsonObj.put("FRemainAmountFor", 0);
		page2JsonObj.put("FRP", 0);
		page2Array.add(page2JsonObj);
		
		JSONArray page3Array = new JSONArray();
		JSONObject page3JsonObj = new JSONObject();
		page3JsonObj.put("FFreeItem3_3", "");
		page3JsonObj.put("FFreeItem4_3", "");
		page3JsonObj.put("FLinkCheckQty", 2);
		page3JsonObj.put("FLinkCheckAmountFor", 102000);
		page3JsonObj.put("FLinkCheckAmount", "");
		page3JsonObj.put("FEntryID3", 1);
		JSONObject itemObj = new JSONObject();
		itemObj.put("FNumber", "01.01.03");
		itemObj.put("FName", "");
		page3JsonObj.put("FItemID", itemObj);
		page3JsonObj.put("FItemID36422", "SX1194JM461");
		page3JsonObj.put("FItemID36436", "");
		JSONObject auxPropObj = new JSONObject();
		auxPropObj.put("FNumber", "");
		auxPropObj.put("FName", "");
		page3JsonObj.put("FAuxPropID", auxPropObj);
		JSONObject unitObj = new JSONObject();
		unitObj.put("FNumber", "01.01");
		unitObj.put("FName", "");
		page3JsonObj.put("FUnitID", unitObj);
		page3JsonObj.put("FBaseUnit", "辆");
		page3JsonObj.put("FAuxQty", 2);
		page3JsonObj.put("FQuantityPayApply_Commit", 0);
		page3JsonObj.put("FQuantityReceive_Commit", 2);
		JSONObject secUnitObj = new JSONObject();
		secUnitObj.put("FNumber", "");
		secUnitObj.put("FName", "");
		page3JsonObj.put("FSecUnitID", secUnitObj);
		page3JsonObj.put("FsecCoefficient", 0);
		page3JsonObj.put("FSecQty", 0);
		page3JsonObj.put("FAuxPrice", 45000);
		page3JsonObj.put("FAuxTaxPrice", 45000);
		page3JsonObj.put("FDiscountRate", 15);
		page3JsonObj.put("FPriceDiscount", 38250);
		page3JsonObj.put("FSourceInterId", 0);
		page3JsonObj.put("FAmtDiscount", 0);
		page3JsonObj.put("FStdAmtDiscount", "");
		page3JsonObj.put("FEntryDisCount", 0);
		page3JsonObj.put("FStdEntryDisCount", "");
		page3JsonObj.put("FAmountExceptDisCount", "");
		page3JsonObj.put("FStdAmountExceptDisCount", "");
		page3JsonObj.put("FAmount3", 40000);
		page3JsonObj.put("FStdAmount", "");
		page3JsonObj.put("FPrice", 45000);
		page3JsonObj.put("FQty", 2);
		page3JsonObj.put("FTaxPrice", 38250);
		page3JsonObj.put("FTaxRate", 17.0);
		page3JsonObj.put("FContractEntryID", 0);
		page3JsonObj.put("FEntryID_SRC", 0);
		page3JsonObj.put("FTaxAmount", 6800);
		page3JsonObj.put("FPayReqPayAmountFor", 0);
		page3JsonObj.put("FOrderType", 0);
		page3JsonObj.put("FStdTaxAmount", "");
		page3JsonObj.put("FOrderEntryID", 0);
		page3JsonObj.put("FOrderInterID", 0);
		page3JsonObj.put("FAmountIncludeTax", 46800);
		page3JsonObj.put("FStdAmountIncludeTax", "");
		page3JsonObj.put("FAllAmountExceptDisCount", "");
		page3JsonObj.put("FStdAllAmountExceptDisCount", "");
		page3JsonObj.put("FAmountMust", 0);
		page3JsonObj.put("FDeductTax", 0);
		page3JsonObj.put("FAuxOrderPrice", 0);
		page3JsonObj.put("FOrderPrice", 0);
		page3JsonObj.put("FNote_3", "");
		page3JsonObj.put("FBatchNo", "");
		JSONObject classIdSrcObj = new JSONObject();
		classIdSrcObj.put("FNumber", "");
		classIdSrcObj.put("FName", "");
		page3JsonObj.put("FClassID_SRC", classIdSrcObj);
		page3JsonObj.put("FSourceBillNo", "");
		page3JsonObj.put("FPayApplyAmountFor", "");
		page3JsonObj.put("FContractBillNo", "");
		page3JsonObj.put("FPayApplyAmount", 0);
		page3JsonObj.put("FOrderBillNo", "");
		page3JsonObj.put("FCheckAmountFor", 46800);
		page3JsonObj.put("FCheckAmount", "");
		page3JsonObj.put("FRemainAmountForEntry", 0);
		page3JsonObj.put("FRemainAmountEntry", "");
		page3JsonObj.put("FCheckQty", 2);
		page3JsonObj.put("FRemainQty", 0);
		page3JsonObj.put("FInvLinkCheckAmount", "");
		page3JsonObj.put("FInvoiceAmount", "");
		page3JsonObj.put("FInvoiceAmountFor", 0);
		page3JsonObj.put("FInvLinkCheckAmountFor", 0);
		page3JsonObj.put("FInvLinkCheckQty", 0);
		page3JsonObj.put("FInvoiceQty", 0);
		page3JsonObj.put("FSourceTranType", 0);
		page3JsonObj.put("FAmountFor_Commit", 46800);
		page3JsonObj.put("FAmount_Commit", "");
		page3JsonObj.put("FSourceEntryID", 0);
		page3Array.add(page3JsonObj);
		
		dataJsonObj.put("Page1", page1Array);
		dataJsonObj.put("Page2", page2Array);
		dataJsonObj.put("Page3", page3Array);
		
		sendJsonObject.put("Data", dataJsonObj);
		System.out.println(JSON.toJSONString(sendJsonObject, SerializerFeature.WriteMapNullValue));
	}

}
